name: .NET Build

on:
  push:
    branches: '*'
    tags-ignore: '*'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up repository name environment variable
        shell: pwsh
        run: |
          $repoName = $env:GITHUB_REPOSITORY.Split('/')[1]
          echo "repo_name=$repoName" >> $env:GITHUB_ENV
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
      - name: Build
        run: |
          dotnet build --no-restore --configuration Release --nologo
      - name: Archive
        run: Compress-Archive -Path ${{ env.repo_name }}/bin/Release/* -DestinationPath ${{ env.repo_name }}.zip
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./${{ env.repo_name }}/bin/Release/*
