name: .NET Build

on:
  push:
    branches: '*'
    tags-ignore: '*'
  pull_request:

jobs:
  get-repo-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Extract repository name
        id: extract_repo_name
        run: |
          REPO_FULL_NAME=${GITHUB_REPOSITORY}
          # Extract repository name from REPO_FULL_NAME
          REPO_NAME=${REPO_FULL_NAME##*/}
          echo "Repository Name: $REPO_NAME"
          # Set the repository name as an output
          echo "repo_name=$REPO_NAME" >> $GITHUB_ENV
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
      - name: Build
        run: |
          dotnet build --no-restore --configuration Release --nologo
      - name: Archive
        run: Compress-Archive -Path ${{ env.repo_name }}/bin/Release/* -DestinationPath ${{ env.repo_name }}.zip
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./${{ env.repo_name }}/bin/Release/*
